export const chatsData = [
  {
    id: 1,
    img: "https://demos.creative-tim.com/soft-ui-dashboard-pro-tailwind/assets/img/kal-visuals-square.jpg",
    name: "Sophie B.",
    msg: "Hi! I need more information..",
  },
  {
    id: 2,
    img: "https://demos.creative-tim.com/soft-ui-dashboard-pro-tailwind/assets/img/marie.jpg",
    name: "Anne Marie",
    msg: "Awesome work, can you..",
  },
  {
    id: 3,
    img: "https://demos.creative-tim.com/soft-ui-dashboard-pro-tailwind/assets/img/ivana-square.jpg",
    name: "Ivanna",
    msg: "About files I can..",
  },
  {
    id: 4,
    img: "https://demos.creative-tim.com/soft-ui-dashboard-pro-tailwind/assets/img/team-4.jpg",
    name: "Peterson",
    msg: "Have a great afternoon..",
  },
  {
    id: 5,
    img: "https://demos.creative-tim.com/soft-ui-dashboard-pro-tailwind/assets/img/team-3.jpg",
    name: "Nick Daniel",
    msg: "Hi! I need more information..",
  },
];

export const productsData = [
  {
    id: 1,
    img: "https://images.unsplash.com/photo-1616627781431-23b776aad6b2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1884&q=80",
    name: "Minimal Bar Stool",
    category: "furniture",
    price: 1469,
    quantity: 8,
    status: "in stock",
    images: [
      "https://images.unsplash.com/photo-1616627781431-23b776aad6b2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1884&q=80",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/chair-steel.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/black-chair.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/chair-pink.jpg",
    ],
  },
  {
    id: 9,
    img: "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/off-white-jacket.jpg",
    name: "Off White Cotton Bomber",
    category: "clothing",
    price: 1869,
    quantity: 4,
    status: "in stock",
    images: [
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/off-white-jacket.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/off-white-jacket.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/off-white-jacket.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/off-white-jacket.jpg",
    ],
  },
  {
    id: 2,
    img: "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/adidas-hoodie.jpg",
    name: "BKLGO Full Zip Hoodie",
    category: "clothing",
    price: 1329,
    quantity: 0,
    status: "out of stock",
    images: [
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/adidas-hoodie.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/off-white-jacket.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/off-white-jacket.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/off-white-jacket.jpg",
    ],
  },
  {
    id: 3,
    img: "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/alchimia-chair.jpg",
    name: "Alchimia Chair",
    category: "Furniture",
    price: 2999,
    quantity: 0,
    status: "out of stock",
    images: [
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/alchimia-chair.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/chair-wood.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/chair-steel.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/black-chair.jpg",
    ],
  },
  {
    id: 4,
    img: "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/yohji-yamamoto.jpg",
    name: "Y-3 Yohji Yamamoto",
    category: "Shoes",
    price: 869,
    quantity: 30,
    status: "in  stock",
    images: [
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/yohji-yamamoto.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/off-white-jacket.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/off-white-jacket.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/off-white-jacket.jpg",
    ],
  },
  {
    id: 5,
    img: "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/undercover.jpg",
    name: "Undercover T-shirt",
    category: "clothing",
    price: 969,
    quantity: 10,
    status: "in  stock",
    images: [
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/undercover.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/off-white-jacket.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/off-white-jacket.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/off-white-jacket.jpg",
    ],
  },
  {
    id: 6,
    img: "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/metro-chair.jpg",
    name: "Metro Bar Stool",
    category: "Furniture",
    price: 969,
    quantity: 41,
    status: "in  stock",
    images: [
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/metro-chair.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/chair-pink.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/black-chair.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/chair-steel.jpg",
    ],
  },
  {
    id: 7,
    img: "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/macbook-pro.jpg",
    name: "MacBook Pro",
    category: "Electronics",
    price: 1869,
    quantity: 0,
    status: "out of stock",
    images: [
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/macbook-pro.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/off-white-jacket.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/off-white-jacket.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/off-white-jacket.jpg",
    ],
  },
  {
    id: 8,
    img: "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/yellow-chair.jpg",
    name: "Luin Floor Lamp",
    category: "Furniture",
    price: 1969,
    quantity: 5,
    status: "in stock",
    images: [
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/yellow-chair.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/chair-pink.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/chair-wood.jpg",
      "https://raw.githubusercontent.com/creativetimofficial/public-assets/master/soft-ui-design-system/assets/img/ecommerce/chair-steel.jpg",
    ],
  },
];

export const colorsThemes = [
  "#ec4899",
  "#4ae635",
  "#09172c",
  "#fb923c",
  "#fa6077",
  "#60a5fa",
];

export const steps = ["product info", "media", "pricing"];

// export const colorsThemes = [
//   ["#ec4899", "#9d174d"],
//   [" #a3e635, #3f6212"],
//   [" #030b17, #1e293b"],
//   ["  #fb923c, #c2410c"],
//   ["   #60a5fa, #3730a3"],
// ];
